declare module '*.module.css';
declare module '*.png';
declare module '*.svg';
declare module 'react-grid-layout';
declare module 'react-geocode';
declare module 'react';
declare module 'react/jsx-runtime';
declare module 'react-dom/client';
declare module '@fullcalendar/react';
