# This is a basic workflow to help you get started with Actions

name: Lint

# Controls when the workflow will run
on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            # Checks-out Node
            - uses: actions/setup-node@v3
              with:
                  node-version: 16

            # Runs compiler and linter for TS files
            - name: Run ESLint
              working-directory: ./walker-backend
              run: |
                  timeout 2m npm install
                  timeout 2m npm run lint

            - name: Run ESLint on frontend
              working-directory: ./walker
              run: |
                  timeout 2m npm install 
                  timeout 2m npm run lint
